geodjango/geodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('',views.home_page, name="home"),
    path('admin/', admin.site.urls),
    path('world/', include('world.urls')),
    path('about',views.about_page, name="about"),
    path('portfolio',views.portfolio_page, name="portfolio"),
    path('blog',views.blog_page, name="blog"),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

geodjango/world/urls.py
from django.urls import path
from django.views.generic import ListView
from djgeojson.views import GeoJSONLayerView
from .models import Things
from . import views

app_name = 'world'

context = {
    'current':'world'
}

urlpatterns = [
    path('add/', views.insert_thing, name="insert_thing"),
    path('map/', views.show_things, name="show_things"),
    path('',views.Home.as_view(), name="map"),
    path('things_data/', views.things_dataset, name='the_things'),
    path('pano_data/', views.pic_dataset, name='pano_imgs'),
    path('show/', views.show360, name = 'show'),
    path('basic/', views.show_basic, name="basic"),
]

geodjango/world/models.py
from django.contrib.gis.db.models import PointField
from django.contrib.gis.db import models
from django.utils.translation import gettext as _

class Things(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField()
    description = models.CharField(max_length=1000)
    geom = models.PointField()

    @property
    def lat_lng(self):
        return list(getattr(self.geom, 'coords', [])[::-1])

    def __unicode__(self):
        return self.title

class PanoImg(models.Model):
    title = models.CharField(max_length=256)
    description = models.CharField(max_length=1000)
    #picture = models.ImageField(upload_to='static/images/',max_length=1000)
    geom = models.PointField()

    def upload(instance, filename):
        ext = filename.split('.')[-1]
        filename = '{}.{}'.format(filename.split('.')[0], ext)
        path = 'static/images/'
        return '{}{}'.format(path,filename)

    picture = models.ImageField('Pano Img',
        upload_to=upload,
        null=True, blank=True,
        help_text=_('Upload Pano Image')
    )

    def upload_thumb(instance, filename):
        ext = filename.split('.')[-1]
        filename = '{}_thumbnail.{}'.format(filename.split('.')[0], ext)
        path = 'static/images/'
        return '{}{}'.format(path, filename)

    picture_tn = models.ImageField('Pano Thumbnail',
        upload_to=upload_thumb,  # callback function
        null=True, blank=True,
        help_text=_('Upload Pano Image Thumbnail')
    )

    def save(self, *args, **kwargs):

        # i moved the logic to signals

        # if not self.slug:
            # self.slug = slugify(self.title)
        super(PanoImg, self).save(*args, **kwargs)

class Blog(models.Model):
    name = models.CharField(max_length=100)

class Author(models.Model):
    name = models.CharField(max_length=200)

class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    authors = models.ManyToManyField(Author)
    headline = models.CharField(max_length=255)
    point = PointField()
    @property
    def lat_lng(self):
        return list(getattr(self.point, 'coords', [])[::-1])

geodjango/world/forms.py
from django.contrib.gis import forms
from django.contrib.gis.db.models import PointField
from . import models

class ThingForm(forms.ModelForm):
    geom = forms.PointField(widget= forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500}) )
    class Meta:
        model = models.Things
        fields = ['title','description','geom',]
#test
#change

geodjango/geodjango/views.py
from django.views import generic
from django.shortcuts import render

def home_page(request):
    context = {
        'current':'home'
    }
    return render(request, 'geodjango/home.html',context)

def about_page(request):
    context = {
        'current':'about'
    }
    return render(request, 'geodjango/about.html',context)

def portfolio_page(request):
    context = {
        'current':'portfolio'
    }
    return render(request, 'geodjango/portfolio.html',context)

def blog_page(request):
    context = {
        'current':'blog'
    }
    return render(request, 'geodjango/blog.html',context)

geodjango/world/views.py
import json
from django.db.models import Value
from django.db.models.functions import Replace
from django.views import generic
from django.contrib.gis.geos import fromstr, Point
from django.contrib.gis.db.models.functions import Distance
from django.http import HttpResponse
from django.core.serializers import serialize
from django.urls import path
from django.shortcuts import render
from .models import Things, PanoImg
from . import forms

my_location = Point(46.870782, -96.788118,srid=4326)

class Home(generic.ListView):
    model = PanoImg
    context_object_name = 'panos'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current'] = 'world'
        return context
    template_name = 'world/things_list.html'

def test(request):
    data = {"hi":"hello"}
    return render(request,"base.html",context={'data':data})

def things_dataset(request):
    thing = serialize('geojson', Things.objects.all())
    return HttpResponse(thing, content_type='json')

def pic_dataset(request):
    pic = serialize('geojson', PanoImg.objects.all() )
    return HttpResponse(pic, content_type='json')

def insert_thing(request):
    if request.method == 'POST':
        form = forms.ThingForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return render(request, 'world/addthing.html', {'form':form})
    else:
        form = forms.ThingForm()
    return render(request, 'world/addthing.html', {'form':form})

def show_things(request):
    return render(request, 'world/showthings.html')

def thing_details(request, slug):
    thing = Things.objects.get(slug=slug)
    return render(request, 'world/thingdetails.html', { 'thing':thing })

def show360(request):
    return render(request, 'world/show360img.html')

def show_basic(request):
    return render(request, 'world/basic.html')

geodjango/geodjango/templates/geodjango/about.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About Page</title>
  </head>
  <body>
    <p>Hello. My name is Tanner Olason. I'm a software developer with experience with
    Python, PHP, JavaScript, AutoHotKey, and Perl. The bulk of my experience is automating
    tasks with scripting languages and creating websites to display the results of those tasks.</p>
    <p>My hobbies include hiking, geolocation games, and photography. All of which seem to overlap
    within my web projects.</p>
  </body>
</html>
{% endblock %}

geodjango/geodjango/templates/geodjango/blog.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  </head>
  <body>

  </body>
</html>
{% endblock %}

geodjango/geodjango/templates/geodjango/home.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
  </head>
  <body>

  </body>
</html>
{% endblock %}

geodjango/geodjango/templates/geodjango/portfolio.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About Page</title>
  </head>
  <body>
  </body>
</html>
{% endblock %}

geodjango/templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<html lang="en" dir="ltr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Tanner Olason's Portfolio</title>
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" />

    <!-- start javascript for header slideshow -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.slideshow.js' %}"></script>
    <script type="text/javascript">
    	$(document).ready(function() {
    		setTimeout(function(){
    		$('.imageNavigation').slideShow({
    			interval: 3
    		});
    		},3000);
    	});
    </script>
    <!-- end javascript for header slideshow -->

    <!-- start lightbox code -->
    <link rel="stylesheet" href="{% static 'css/jquery.lightbox-0.5.css' %}" type="text/css" />
    <script type="text/javascript" src="{% static 'js/jquery.lightbox-0.5.pack.js' %}"></script>
    <script type="text/javascript">
    $(function() {
    	$('.lightbox').lightBox();
    });
    </script>
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <div id="logo"><a class="nav-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.jpg' %}" method="post"></a></div>
        <!--end logo-->
        <!--start main menu-->
        <div id="menucontainer">
          <ul>

            <li><a href="{% url 'home' %}"
              {% if current == 'home' %}
                class='current'
              {% endif %} >Home <br />
              <span>where it begins</span></a></li>
            <li><a href="{% url 'world:map' %}"
              {% if current == 'world' %}
                class='current'
              {% endif %} >World Map <br />
              <span>Photos</span></a></li>
            <li><a href="{% url 'portfolio' %}"
              {% if current == 'portfolio' %}
                class='current'
              {% endif %} >Portfolio <br />
              <span>my work</span></a></li>
            <li><a href="{% url 'blog' %}"
              {% if current == 'blog' %}
                class='current'
              {% endif %} >Blog <br />
              <span>Articles &amp; Info</span></a></li>
            <li><a href="{% url 'about' %}"
              {% if current == 'about' %}
                class='current'
              {% endif %} >About <br />
              <span>Who I am</span></a></li>
          </ul>
        </div>
        <!--end main menu-->
      </div>
      <!--end header-->
    </div>
    <div id="wrapper2">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

geodjango/world/templates/world/addthing.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {{ geoform.media }}
    {{ form.media }}
    <meta charset="utf-8">
    <title>add a thing?</title>
  </head>
  <body>
    <h1>Add a location to the map. Simple!</h1>
    <div id="map">
      <form class="multipart/form-data" action="" method="post">
        {% csrf_token %}
          {{ form.as_p }}
        <input type="submit" name="Submit" />
      </form>
      <div id="m" style="width: 1920px; height: 1080px;">
      </div>

    </div>
  </body>
</html>

geodjango/world/templates/world/basic.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>About Page</title>

  </head>
  <body>

    <a-scene embedded><a-sky src="http://127.0.0.1:8000/world/media/static/images/R0010217_20210830104636.JPG"></a-sky></a-scene>
  </body>
</html>
{% endblock %}

geodjango/world/templates/world/show360img.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <title>About Page</title>

  </head>
  <body>
    <script type="text/javascript">
      window.onload = function(){
        function getPhoto(name, url) {
          if (!url) url = window.location.href;
          name = name.replace(/[\[\]]/g, '\\$&');
          var reg = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
            results = reg.exec(url);
          if (!results) return null;
          if (!results[2]) return '';
          return decodeURIComponent(results[2].replace(/\+/g, ' '));
        }
        var pic = getPhoto('link');
        var insert = "<a-scene embedded><a-sky src=../"+pic+"></a-sky></a-scene>"
        //var insert = '<a-scene embedded><a-sky src="http://127.0.0.1:8000/world/media/static/images/R0010217_20210830104636.JPG"></a-sky></a-scene>'
        //var insert = '<h1>"http://127.0.0.1:8000/world/media/static/images/R0010217_20210830104636.JPG"</h1>'
        //alert(insert)
        document.getElementById('wrapper2').innerHTML = insert;
      }
    </script>
  </body>
</html>
{% endblock %}

geodjango/world/templates/world/showthings.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>A Map of Things!</title>
  </head>
  <body>
    <h1>Thing Map</h1>
    {% for thing in Things %}
    <h2>thing:{{thing.name}}</h2>
    {% endfor %}

  </body>
</html>

geodjango/world/templates/world/things_list.html
{% extends 'base.html' %}



<!DOCTYPE html>
{% block content %}
{% load static %}
{% load leaflet_tags %}


  <head>
    <meta charset="utf-8">
    {% leaflet_js %}
    {% leaflet_css %}
    <script src="{% static 'leaflet.ajax.js' %}" charset="utf-8"></script>
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />
    <title>360 Photo Map</title>
  </head>
  <body>
    <script type="text/javascript">

      function place_pos(map,options){
        var dataset = L.geoJson.ajax("{% url 'world:pano_imgs' %}",{
          onEachFeature: function(feature, layer) {
            var str = feature.properties.picture.replace("static/","media/static/")
            var thumb = str.replace(".JPG","_thumbnail.JPG")
            layer.bindPopup("<div class='pin'><h1>"+feature.properties.title+"</h1><br><p>Click the picture to view the 360 photo.</p><a href={% url 'world:show' %}?link="+str+" ><img src="+thumb+"></a></div>",
          {
            maxWidth: "800px",
            maxHeight: "800px",

        })
          }
        });
        dataset.addTo(map)


      }


    </script>
    <style>
      html, body {
        height: 100%;
      }
      .leaflet-popup-pane {
        color: #B6CEE2;
        text-align: center;
      }
      .leaflet-container {  /* all maps */
          width:  100%;
          height: 100%;
      }

      #specialbigmap {
          height: 800px;
      }

      /* Resize the "display_raw" textbox */
      .django-leaflet-raw-textarea {
          width: 100%;
      }
      #pin {
        color: #B6CEE2;
        text-align: center;
      }
    </style>

    {% leaflet_map "gis" callback="window.place_pos" %}
  </body>

{% endblock %}